### ISSUE TITLE
missing values in chain

### ISSUE THREAD

**Issue by vrabaud** [moveit/moveit_setup_assistant#62] opened 2013-10-29 15:30 UTC
With 0.5.4 and trying to add values to the chain of a group, I get missing values:
I am on Kubuntu 13.04 (not sure if this is a display bug

![moveit](https://f.cloud.github.com/assets/700766/1429184/dec0535c-40ae-11e3-9ee7-baa3973923a0.png)

**Comment by isucan** [comment] 2013-10-30 08:46
I am not sure I understand what the problem is. Is there missing information in the tree being displayed?

**Comment by vrabaud** [comment] 2013-10-30 09:26
yes, a lot of things are missing (see the empty branches on the left?). E.g., RHand that I chose is valid but is not being displayed.

**Comment by isucan** [comment] 2013-10-30 09:34
I RHand not under RShoulder?

**Comment by vrabaud** [comment] 2013-10-30 17:13
ok it is :) I guess it is just a display issue then. It is weird to have those empty branches on the left.

**Comment by isucan** [comment] 2013-10-30 18:51
ok :) i am closing this then.

**Closed as completed by isucan** 2013-10-30 18:51 UTC
