### ISSUE TITLE
Problem parsing pose values

### ISSUE THREAD

**Issue by VictorLamoine** [moveit/moveit_setup_assistant#107] opened 2015-09-18 08:09 UTC
When adding a custom robot pose with joint values different from zero, the values are saved with the locale separator (`,` in my case). This leads to an error when trying the `demo.launch` because the value cannot be parsed:

``` bash
[ERROR] [1442563400.767605554]: Unable to parse joint value '-1,5707'
```

This can be easily fixed by replacing the `,` with a `.` in the generated SRDF.

Something like that should fix the issue:

```
doublespinbox->setLocale(QLocale(QLocale::English));
```

**Comment by gavanderhoorn** [comment] 2016-02-11 08:37
Duplicate of #51?

**Comment by VictorLamoine** [comment] 2016-02-11 11:18
Yes it is a duplicate of that issue.

**Comment by rhaschke** [comment] 2016-07-28 12:49
Fixed with #123.

**Closed as completed by rhaschke** 2016-07-28 12:49 UTC
