### ISSUE TITLE
Generate Package always overwrites package.xml

### ISSUE THREAD

**Issue by sssmanufacturing** [moveit/moveit_setup_assistant#86] opened 2014-06-27 00:35 UTC
When changing arm configurations using the setup assistant, even if package.xml is unchecked from the list, it gets overwritten. All other files appear to obey the check boxes.

**Comment by davetcoleman** [comment] 2014-07-01 06:38
I have confirmed this bug.

**Comment by davetcoleman** [comment] 2014-07-01 07:17
This is very strange - I started debugging this issue just now and could not find any code that would cause the behavior. Then, without any code changes except debug info, the bug went away. It seems recompiling fixed the issue, because I then reverted all changes and still couldn't reproduce the bug. My guess is that there is some issue with the index value of `0`, perhaps its because I'm converting the index to a user role in Qt widgets:

```
item->setData(Qt::UserRole, QVariant(i));
```

Are you running from debians or source? Could you try compiling from source to confirm the issue? I'm not sure what to do now, perhaps a change to Qt caused this.

**Comment by hersh** [comment] 2014-07-03 16:18
Closing as not reproducible.  If someone finds a way to reproduce it, please reopen.

**Closed as completed by hersh** 2014-07-03 16:18 UTC
